import HorizontalLine from "../horizontalLine/HorizontalLine";

import "./Faq.css";

function Faq() {
  return (
    <div className="faq">
      <h2 className="page-heading">FAQ</h2>
      <HorizontalLine />
      <div className="faq__container">
        <h3 className="faq__question">Q1. How do you generate images?</h3>
        <p className="faq__answer">
          A1. The image you want to generate can be generated by specifying the
          image in Japanese. (Example: Japanese, female, black hair, working
          adult) <br />
          If you have an image that is similar to the image, you can generate a
          similar image by loading that image.
        </p>
      </div>
      <div className="faq__container">
        <h3 className="faq__question">Q2. How do you generate images?</h3>
        <p className="faq__answer">
          A1. The image you want to generate can be generated by specifying the
          image in Japanese. (Example: Japanese, female, black hair, working
          adult) <br />
          If you have an image that is similar to the image, you can generate a
          similar image by loading that image.
        </p>
      </div>

      <div className="faq__container">
        <h3 className="faq__question">Q3. How do you generate images?</h3>
        <p className="faq__answer">
          A1. The image you want to generate can be generated by specifying the
          image in Japanese. (Example: Japanese, female, black hair, working
          adult) <br />
          If you have an image that is similar to the image, you can generate a
          similar image by loading that image.
        </p>
      </div>
    </div>
  );
}

export default Faq;
